### ISSUE TITLE
Using Binary Media Types in API Gateway causes OPTIONS requests failing with 500 errors

### ISSUE THREAD

**Issue by frankyhun** [squidfunk/terraform-aws-api-gateway-enable-cors#10]
By using Binary Media Types set to `*/*` in API Gateway cause OPTIONS requests failing with 500 errors. As a solution, the content_handling should be set to CONVERT_TO_TEXT in the aws_api_gateway_integration resource, see:
https://forums.aws.amazon.com/thread.jspa?threadID=256140

**Comment by squidfunk** [comment]
Released as part of 0.3.2.
