### ISSUE TITLE
Deprecation warnings after upgrading to Terraform 0.12

### ISSUE THREAD

**Issue by adamjace** [squidfunk/terraform-aws-api-gateway-enable-cors#8]
After upgrading Terraform to 0.12 there appears to be multiple deprecation warnings coming from this library:

Warning: Interpolation-only expressions are deprecated
Warning: Quoted references are deprecated
Warning: Quoted type constraints are deprecated

Are there any plans to address these?

Update: I see there is an open PR for this already:

https://github.com/squidfunk/terraform-aws-api-gateway-enable-cors/pull/6/files

Thanks

**Comment by squidfunk** [comment]
Should be fixed as of 0.3.1
